# Maintainer: FlorianNAdam
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=persistent-evdev-rs-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Persistent proxy for evdev devices"
url="https://github.com/FlorianNAdam/persistent-input-rs"
license=("MIT")
arch=("x86_64")
provides=("persistent-evdev-rs")
conflicts=("persistent-evdev-rs")
source=("https://github.com/FlorianNAdam/persistent-input-rs/releases/download/v$pkgver/persistent-evdev-rs-$pkgver-x86_64.tar.gz")
sha256sums=("27d7f5d9d3279637f19add5c2ccbfdb01dacb2163bc59882d0a2d38e2d00bd54")

package() {
    install -Dm755 persistent-evdev-rs -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE.md "$pkgdir/usr/share/licenses/$pkgname/LICENSE.md"
}
